api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Apache HTTPD server"
  homepage = "https://github.com/paketo-buildpacks/httpd"
  id = "paketo-buildpacks/httpd"
  keywords = ["apache", "httpd", "server", "distribution"]
  name = "Paketo Buildpack for Apache HTTP Server"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:bf8c75c148429dd1c97be0d3ad477ee97f31400b15c5224517a4c982b9b4d637"
    cpe = "cpe:2.3:a:apache:http_server:2.4.69:*:*:*:*:*:*:*"
    id = "httpd"
    licenses = ["Apache-2.0"]
    name = "Apache HTTP Server"
    os = "linux"
    purl = "pkg:generic/httpd@2.4.69?checksum=c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d&download_url=http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source-checksum = "sha256:c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/httpd/httpd_2.4.69_linux_amd64_jammy_bf8c75c1.tgz"
    version = "2.4.69"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:e4c212ed4c6484f2702f2c24f42c33ae6c2f52051e3425045047cc11db9deec9"
    cpe = "cpe:2.3:a:apache:http_server:2.4.69:*:*:*:*:*:*:*"
    id = "httpd"
    licenses = ["Apache-2.0"]
    name = "Apache HTTP Server"
    os = "linux"
    purl = "pkg:generic/httpd@2.4.69?checksum=c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d&download_url=http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source-checksum = "sha256:c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/httpd/httpd_2.4.69_linux_arm64_jammy_e4c212ed.tgz"
    version = "2.4.69"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:45035a184c4ba35d5c277c40fa1f5a72b1a414d3080fee48bba9d1e6cbb502d6"
    cpe = "cpe:2.3:a:apache:http_server:2.4.69:*:*:*:*:*:*:*"
    id = "httpd"
    licenses = ["Apache-2.0"]
    name = "Apache HTTP Server"
    os = "linux"
    purl = "pkg:generic/httpd@2.4.69?checksum=c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d&download_url=http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source-checksum = "sha256:c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/httpd/httpd_2.4.69_linux_amd64_noble_45035a18.tgz"
    version = "2.4.69"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:bd4d2f4088de429dd5f3cde81510d8f09081362b9e72f78c895c4a9939249c51"
    cpe = "cpe:2.3:a:apache:http_server:2.4.69:*:*:*:*:*:*:*"
    id = "httpd"
    licenses = ["Apache-2.0"]
    name = "Apache HTTP Server"
    os = "linux"
    purl = "pkg:generic/httpd@2.4.69?checksum=c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d&download_url=http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source-checksum = "sha256:c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/httpd/httpd_2.4.69_linux_arm64_noble_bd4d2f40.tgz"
    version = "2.4.69"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:96468a2180829bbebe645d69e97ef3fc414113771cbeee9ed45f1d0648d1190d"
    cpe = "cpe:2.3:a:apache:http_server:2.4.69:*:*:*:*:*:*:*"
    id = "httpd"
    licenses = ["Apache-2.0"]
    name = "Apache HTTP Server"
    os = "linux"
    purl = "pkg:generic/httpd@2.4.69?checksum=c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d&download_url=http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source-checksum = "sha256:c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d"
    stacks = ["io.buildpacks.stacks.resolute"]
    uri = "https://artifacts.paketo.io/httpd/httpd_2.4.69_linux_amd64_resolute_96468a21.tgz"
    version = "2.4.69"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:3eb838ea44af1a3f6e78134d1ef95efea5d05aeaeacd61f15aed41a53ee43d3c"
    cpe = "cpe:2.3:a:apache:http_server:2.4.69:*:*:*:*:*:*:*"
    id = "httpd"
    licenses = ["Apache-2.0"]
    name = "Apache HTTP Server"
    os = "linux"
    purl = "pkg:generic/httpd@2.4.69?checksum=c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d&download_url=http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.69.tar.bz2"
    source-checksum = "sha256:c5e6ebc66e349b87d7fc6916ae7cc2a808ed348003de134cf9e9d89d3e2cc73d"
    stacks = ["io.buildpacks.stacks.resolute"]
    uri = "https://artifacts.paketo.io/httpd/httpd_2.4.69_linux_arm64_resolute_3eb838ea.tgz"
    version = "2.4.69"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "httpd"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[stacks]]
  id = "io.buildpacks.stacks.resolute"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
